# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import DataMigration
from django.db import models

class Migration(DataMigration):

    def forwards(self, orm):
        "Write your forwards methods here."
        # Note: Don't use "from appname.models import ModelName". 
        # Use orm.ModelName to refer to models in this application,
        # and orm['appname.ModelName'] for models in other applications.

    def backwards(self, orm):
        "Write your backwards methods here."

    models = {
        'snh.dailymotionharvester': {
            'Meta': {'object_name': 'DailyMotionHarvester'},
            'current_harvest_start_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'current_harvested_user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'current_harvested_user'", 'null': 'True', 'to': "orm['snh.DMUser']"}),
            'dmusers_to_harvest': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'dmusers_to_harvest'", 'symmetrical': 'False', 'to': "orm['snh.DMUser']"}),
            'dont_harvest_further_than': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'full_harvest_on_next_run': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'harvest_in_progress': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'harvest_window_from': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'harvest_window_to': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'harvester_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'harvester_type': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'key': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'last_harvest_end_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'last_harvest_start_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'last_harvested_user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'last_harvested_user'", 'null': 'True', 'to': "orm['snh.DMUser']"}),
            'last_user_harvest_was_aborted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'max_retry_on_fail': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'retry_user_after_abortion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'secret': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'user': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'})
        },
        'snh.dmcomment': {
            'Meta': {'object_name': 'DMComment'},
            'created_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'fid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'language': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'locked': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'message': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmcomment.user'", 'null': 'True', 'to': "orm['snh.DMUser']"}),
            'video': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmcomment.video'", 'to': "orm['snh.DMVideo']"})
        },
        'snh.dmuser': {
            'Meta': {'object_name': 'DMUser'},
            'avatar_large_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmuser.avatar_large_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'avatar_medium_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmuser.avatar_medium_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'avatar_small_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmuser.avatar_small_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'created_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'error_triggered': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'fans': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'dmuser.fans'", 'symmetrical': 'False', 'to': "orm['snh.DMUser']"}),
            'fid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'following': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'dmuser.following'", 'symmetrical': 'False', 'to': "orm['snh.DMUser']"}),
            'friends': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'dmuser.friends'", 'symmetrical': 'False', 'to': "orm['snh.DMUser']"}),
            'ftype': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'language': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'screenname': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'updated_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmuser.url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'username': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'videos_total': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'videostar': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmuser.videostar'", 'null': 'True', 'to': "orm['snh.DMVideo']"}),
            'views_total': ('django.db.models.fields.IntegerField', [], {'null': 'True'})
        },
        'snh.dmvideo': {
            'Meta': {'object_name': 'DMVideo'},
            'allow_comments': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'aspect_ratio': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '13', 'decimal_places': '12'}),
            'bookmarks_total': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'comments_total': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'created_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'duration': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'embed_html': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'embed_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmvideo.embed_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'encoding_progress': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'explicit': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'fid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'ftype': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'geoblocking': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'in_3d': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'isrc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'language': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'live_publish_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmvideo.live_publish_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'mode': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'modified_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'onair': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'paywall': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'private': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'published': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'rating': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'ratings_total': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'rental_duration': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'swf_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmvideo.swf_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'tag': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'tags': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'taken_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'thumbnail_large_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmvideo.thumbnail_large_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'thumbnail_medium_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmvideo.thumbnail_medium_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'thumbnail_small_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmvideo.thumbnail_small_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'thumbnail_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmvideo.thumbnail_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'tiny_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmvideo.tiny_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'title': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'upc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmvideo.url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'dmvideo.user'", 'to': "orm['snh.DMUser']"}),
            'video_file_path': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'views_last_day': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'views_last_hour': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'views_last_month': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'views_last_week': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'views_total': ('django.db.models.fields.IntegerField', [], {'null': 'True'})
        },
        'snh.facebookharvester': {
            'Meta': {'object_name': 'FacebookHarvester'},
            'current_harvest_start_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'dont_harvest_further_than': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'fbusers_to_harvest': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'fbusers_to_harvest'", 'symmetrical': 'False', 'to': "orm['snh.FBUser']"}),
            'full_harvest_on_next_run': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'harvest_in_progress': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'harvest_window_from': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'harvest_window_to': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'harvester_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'harvester_type': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_harvest_end_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'last_harvest_start_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'last_user_harvest_was_aborted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'max_retry_on_fail': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'retry_user_after_abortion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'update_likes': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        'snh.fbcomment': {
            'Meta': {'object_name': 'FBComment'},
            'created_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'error_on_update': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ffrom': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'fbcomment.ffrom'", 'null': 'True', 'to': "orm['snh.FBUser']"}),
            'fid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'unique': 'True', 'null': 'True'}),
            'ftype': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'likes': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'message': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'post': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['snh.FBPost']", 'null': 'True'}),
            'user_likes': ('django.db.models.fields.IntegerField', [], {'null': 'True'})
        },
        'snh.fbpost': {
            'Meta': {'object_name': 'FBPost'},
            'application_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'caption': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'comments_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'created_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'error_on_update': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ffrom': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'fbpost.from'", 'null': 'True', 'to': "orm['snh.FBUser']"}),
            'fid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'unique': 'True', 'null': 'True'}),
            'ftype': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'icon': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'fbpost.icon'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'likes_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'likes_from': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "'fbpost.likes_from'", 'null': 'True', 'to': "orm['snh.FBUser']"}),
            'link': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'fbpost.link'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'message': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'message_tags_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'object_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True'}),
            'picture': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'fbpost.picture'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'place_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'privacy_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'properties_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'shares_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'source': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'fbpost.source'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'story': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'story_tags_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'updated_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['snh.FBUser']"})
        },
        'snh.fbresult': {
            'Meta': {'object_name': 'FBResult'},
            'fid': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'ftype': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'harvester': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['snh.FacebookHarvester']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'parent': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'result': ('django.db.models.fields.TextField', [], {'null': 'True'})
        },
        'snh.fbuser': {
            'Meta': {'object_name': 'FBUser'},
            'about': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'bio': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'birthday': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'category': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'checkins': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'education_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'email': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'error_on_update': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'error_triggered': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'favorite_athletes_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'favorite_teams_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'fid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'unique': 'True', 'null': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'hometown': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'installed_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'interested_in_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'languages_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'likes': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'link': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'fbuser.link'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'locale': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'location_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'phone': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'picture': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'fbpagedesc.picture'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'political': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'quotes': ('django.db.models.fields.TextField', [], {'max_length': '255', 'null': 'True'}),
            'relationship_status': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'religion': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'significant_other_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'talking_about_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'third_party_id': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'timezone_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'updated_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'max_length': '255', 'unique': 'True', 'null': 'True'}),
            'verified': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'video_upload_limits_raw': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'website': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'fbuser.website'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'work_raw': ('django.db.models.fields.TextField', [], {'null': 'True'})
        },
        'snh.image': {
            'Meta': {'object_name': 'Image'},
            'name': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'snh.tag': {
            'Meta': {'object_name': 'Tag'},
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'text': ('django.db.models.fields.TextField', [], {'null': 'True'})
        },
        'snh.twitterharvester': {
            'Meta': {'object_name': 'TwitterHarvester'},
            'access_token_key': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'access_token_secret': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'consumer_key': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'consumer_secret': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'current_harvest_start_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'current_harvested_user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'current_harvested_user'", 'null': 'True', 'to': "orm['snh.TWUser']"}),
            'dont_harvest_further_than': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'full_harvest_on_next_run': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'harvest_in_progress': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'harvest_window_from': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'harvest_window_to': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'harvester_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'harvester_type': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'hourly_limit': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_harvest_end_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'last_harvest_start_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'last_harvested_user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'last_harvested_user'", 'null': 'True', 'to': "orm['snh.TWUser']"}),
            'last_user_harvest_was_aborted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'max_retry_on_fail': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'remaining_hits': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'reset_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'reset_time_in_seconds': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'retry_user_after_abortion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'twsearch_to_harvest': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'twitterharvester.twsearch_to_harvest'", 'symmetrical': 'False', 'to': "orm['snh.TWSearch']"}),
            'twusers_to_harvest': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'twusers_to_harvest'", 'symmetrical': 'False', 'to': "orm['snh.TWUser']"})
        },
        'snh.twsearch': {
            'Meta': {'object_name': 'TWSearch'},
            'latest_status_harvested': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'TWSearch.latest_status_harvested'", 'null': 'True', 'to': "orm['snh.TWStatus']"}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'status_list': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'twsearch.status_list'", 'symmetrical': 'False', 'to': "orm['snh.TWStatus']"}),
            'term': ('django.db.models.fields.TextField', [], {'null': 'True'})
        },
        'snh.twstatus': {
            'Meta': {'object_name': 'TWStatus'},
            'created_at': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'error_on_update': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'favorited': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'fid': ('django.db.models.fields.BigIntegerField', [], {'unique': 'True', 'null': 'True'}),
            'hash_tags': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'twstatus_tag'", 'symmetrical': 'False', 'to': "orm['snh.Tag']"}),
            'model_update_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'retweet_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'retweeted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'source': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'text': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'text_urls': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'twstatus_text_urls'", 'symmetrical': 'False', 'to': "orm['snh.URL']"}),
            'truncated': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'postedStatuses'", 'to': "orm['snh.TWUser']"}),
            'user_mentions': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'mentionedInStatuses'", 'symmetrical': 'False', 'to': "orm['snh.TWUser']"})
        },
        'snh.twuser': {
            'Meta': {'object_name': 'TWUser'},
            'created_at': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'error_on_update': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'error_triggered': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'favourites_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'fid': ('django.db.models.fields.BigIntegerField', [], {'unique': 'True', 'null': 'True'}),
            'followers_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'friends_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'lang': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'last_harvested_status': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'TWStatus.last_harvested_status'", 'null': 'True', 'to': "orm['snh.TWStatus']"}),
            'listed_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'location': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'model_update_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'profile_background_color': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'profile_background_image_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'twuser.profile_background_image_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'profile_background_tile': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_image_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'twuser.profile_image_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'profile_link_color': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'profile_sidebar_fill_color': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'profile_text_color': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'protected': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'screen_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'unique': 'True', 'null': 'True'}),
            'statuses_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'time_zone': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'twuser.url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'utc_offset': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'was_aborted': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        'snh.url': {
            'Meta': {'object_name': 'URL'},
            'original_url': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'snapshot_file_path': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'take_snapshot': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'unshorten_url': ('django.db.models.fields.TextField', [], {'null': 'True'})
        },
        'snh.youtubeharvester': {
            'Meta': {'object_name': 'YoutubeHarvester'},
            'current_harvest_start_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'current_harvested_user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'current_harvested_user'", 'null': 'True', 'to': "orm['snh.YTUser']"}),
            'dev_key': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'dont_harvest_further_than': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'full_harvest_on_next_run': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'harvest_in_progress': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'harvest_window_from': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'harvest_window_to': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'harvester_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'harvester_type': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_harvest_end_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'last_harvest_start_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'last_harvested_user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'last_harvested_user'", 'null': 'True', 'to': "orm['snh.YTUser']"}),
            'last_user_harvest_was_aborted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'max_retry_on_fail': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'retry_user_after_abortion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ytusers_to_harvest': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'ytusers_to_harvest'", 'symmetrical': 'False', 'to': "orm['snh.YTUser']"})
        },
        'snh.ytcomment': {
            'Meta': {'object_name': 'YTComment'},
            'fid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'message': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'published': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'updated': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'ytcomment.user'", 'null': 'True', 'to': "orm['snh.YTUser']"}),
            'video': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'ytcomment.video'", 'to': "orm['snh.YTVideo']"})
        },
        'snh.ytuser': {
            'Meta': {'object_name': 'YTUser'},
            'age': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'books': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'company': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'error_triggered': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'fid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'hobbies': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'hometown': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'last_web_access': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'link': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'ytuser.link'", 'symmetrical': 'False', 'to': "orm['snh.URL']"}),
            'location': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'movies': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'music': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'occupation': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'relationship': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'school': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'subscriber_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'updated_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'uri': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'ytuser.uri'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'username': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'video_watch_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'view_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'})
        },
        'snh.ytvideo': {
            'Meta': {'object_name': 'YTVideo'},
            'category': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'duration': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'favorite_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'fid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'player_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'ytvideo.player_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'pmk_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'published': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'recorded': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'swf_url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'ytvideo.swf_url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'title': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'updated': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'url': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'ytvideo.url'", 'null': 'True', 'to': "orm['snh.URL']"}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'ytvideo.user'", 'to': "orm['snh.YTUser']"}),
            'video_file_path': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'view_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'})
        }
    }

    complete_apps = ['snh']
    symmetrical = True
